name: Platform Tests & Build
on: [push]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set Version
      run: make set-version
      
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: sudo apt-get update && sudo apt install -y bc make libgl1-mesa-dev xorg-dev gcc-multilib gcc-mingw-w64
      if: ${{ runner.os == 'Linux' }}

    #- name: Tests
    #  run: go test -tags ci ./...

    #- name: Wayland Tests
    #  run: go test -tags ci,wayland ./...
    #  if: ${{ runner.os == 'Linux' }}
    
    - name: Build binaries
      env:
        GOOS: linux
        GOARCH: amd64
      working-directory: .
      run: |
        make build-linux
        #make build-windows
      if: ${{runner.os == 'Linux'}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.VERSION }}.${{ github.run_number }}"
        prerelease: true
        title: "${{ env.VERSION }}.${{ github.run_number }}"
        files: |
          bin/quail-linux-x64
          bin/quail-win-x64.exe
          bin/quail-darwin-x64
